#! /bin/sh

### BEGIN INIT INFO
# Provides:          flatkvm-boot
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:    rmnologin
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Provide limited super user privileges to specific users
# Description: Provide limited super user privileges to specific users.
### END INIT INFO

. /lib/lsb/init-functions

N=/etc/init.d/flatkvm-boot

set -e

case "$1" in
  start)
	FLATKVM_UID=$(sed -E 's/.*flatkvm_uid=([0-9]+)?.*/\1/' /proc/cmdline)

	if [ -z "${FLATKVM_UID}" ]; then
	        FLATKVM_UID=500
	fi                                                                                                
	echo "flatkvm:x:${FLATKVM_UID}:${FLATKVM_UID}:Linux User,,,:/home/flatkvm:/bin/bash" >> /etc/passwd
	echo "flatkvm:x:${FLATKVM_UID}:flatkvm" >> /etc/group
 
	chown -R ${FLATKVM_UID}:${FLATKVM_UID} /home/flatkvm
	;;
  stop|reload|restart|force-reload|status)
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
